[package]
name = "result_guide_gui"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }
eframe = "0.21.0"
egui_extras = "0.21.0"
rayon = "1.6.1"
reqwest = {version = "0.11", features = ["blocking"]}

entities = {path = "../entities"}
